import type { CoCreationPost } from "./types"

export const CURRENT_USER_ID = "user-001"

export const mockPosts: CoCreationPost[] = [
  {
    id: "0",
    title: "这是一个测试标题正好有二十三个字符看效果",
    description: "这是一个用于测试标题长度显示效果的帖子，验证标题超长时是否正确显示省略号。",
    initiator: "测试公司",
    budget: "5000",
    expectedOutput: "测试报告",
    domainTags: ["人工智能", "教育培训"],
    customTags: ["测试", "标题显示"],
    descriptionFiles: [],
    resourceFiles: [],
    endDate: "2026-05-20",
    contactEmail: "test@example.com",
    contactPhone: "188****8888",
    contactWeChat: "test_user",
    contactQQ: "888888888",
    createdAt: "2026-03-12",
    authorId: "user-010",
    authorName: "测试用户",
    status: "共创中"
  },
  {
    id: "1",
    title: "智能家居场景交互设计共创",
    description: "希望与设计师、开发者共同探讨智能家居场景下的人机交互方式，包括语音控制、手势识别、情景模式等方面的创新设计。我们将一起头脑风暴，产出创新的交互方案。",
    initiator: "智能科技有限公司",
    budget: "20000",
    expectedOutput: "交互设计方案",
    domainTags: ["智能制造", "物联网"],
    customTags: ["交互设计", "用户体验"],
    descriptionFiles: [],
    resourceFiles: [],
    endDate: "2026-04-10",
    contactEmail: "zhang@design.com",
    contactPhone: "138****1234",
    contactWeChat: "designer_zhang",
    contactQQ: "123456789",
    createdAt: "2026-03-01",
    authorId: "user-001",
    authorName: "张设计",
    status: "共创中"
  },
  {
    id: "2",
    title: "社区团购小程序功能优化",
    description: "现有社区团购小程序需要优化用户体验，寻找产品经理和前端开发者共同参与功能迭代，重点优化下单流程和配送跟踪功能。",
    initiator: "社区优选团队",
    budget: "15000",
    expectedOutput: "产品优化方案",
    domainTags: ["电子商务", "零售消费"],
    customTags: ["小程序", "产品优化"],
    descriptionFiles: [],
    resourceFiles: [],
    endDate: "2026-04-15",
    contactEmail: "li@product.com",
    contactPhone: "139****5678",
    contactWeChat: "pm_li",
    contactQQ: "987654321",
    createdAt: "2026-03-05",
    authorId: "user-002",
    authorName: "李产品",
    status: "共创中"
  },
  {
    id: "3",
    title: "在线教育平台课程体系设计",
    description: "正在筹备一个面向职场人士的在线教育平台，需要教育专家和内容创作者共同参与课程体系的设计和内容规划。",
    initiator: "学无止境教育",
    budget: "30000",
    expectedOutput: "课程体系文档",
    domainTags: ["教育培训"],
    customTags: ["课程设计", "内容创作"],
    descriptionFiles: [],
    resourceFiles: [],
    endDate: "2026-03-01",
    contactEmail: "wang@edu.com",
    contactPhone: "137****9012",
    contactWeChat: "edu_wang",
    contactQQ: "456789123",
    createdAt: "2026-01-25",
    authorId: "user-003",
    authorName: "王教育",
    status: "已结束"
  },
  {
    id: "4",
    title: "健身APP社交功能共创",
    description: "我们的健身APP计划增加社交功能，希望找到健身爱好者和社交产品专家一起探讨如何让用户在运动中建立联系。",
    initiator: "健康生活APP",
    budget: "25000",
    expectedOutput: "功能设计稿",
    domainTags: ["医疗健康"],
    customTags: ["健身", "社交", "移动应用"],
    descriptionFiles: [],
    resourceFiles: [],
    endDate: "2026-05-01",
    contactEmail: "chen@fitness.com",
    contactPhone: "136****3456",
    contactWeChat: "fitness_chen",
    contactQQ: "789123456",
    createdAt: "2026-03-07",
    authorId: "user-004",
    authorName: "陈运动",
    status: "共创中"
  },
  {
    id: "5",
    title: "企业知识管理系统架构设计",
    description: "大型企业内部知识管理系统的技术架构设计，需要后端架构师和AI工程师共同参与，探讨知识图谱和智能推荐的实现方案。",
    initiator: "张设计工作室",
    budget: "50000",
    expectedOutput: "技术架构文档",
    domainTags: ["人工智能", "智能制造"],
    customTags: ["知识管理", "企业软件"],
    descriptionFiles: [],
    resourceFiles: [],
    endDate: "2026-04-30",
    contactEmail: "liu@tech.com",
    contactPhone: "135****7890",
    contactWeChat: "tech_liu",
    contactQQ: "321654987",
    createdAt: "2026-02-20",
    authorId: "user-001",
    authorName: "张设计",
    status: "待审核"
  },
  {
    id: "12",
    title: "智能客服系统升级方案",
    description: "对现有智能客服系统进行升级，引入大模型能力，提升客户服务质量。需要AI工程师和客服运营专家参与。",
    initiator: "张设计工作室",
    budget: "80000",
    expectedOutput: "系统升级方案",
    domainTags: ["人工智能", "电子商务"],
    customTags: ["智能客服", "大模型"],
    descriptionFiles: [],
    resourceFiles: [],
    endDate: "2026-05-20",
    contactEmail: "test@example.com",
    contactPhone: "188****8888",
    contactWeChat: "test_user",
    contactQQ: "888888888",
    createdAt: "2026-03-13",
    authorId: "user-001",
    authorName: "张设计",
    status: "审核未通过",
    rejectionReason: "场景描述不够具体，请补充以下内容：1. 明确智能客服系统当前存在的具体问题；2. 说明引入大模型后期望达到的具体效果指标；3. 补充项目预期时间节点和里程碑。"
  },
  {
    id: "6",
    title: "儿童编程教育游戏化设计",
    description: "设计一款面向6-12岁儿童的编程启蒙游戏，需要游戏设计师、教育专家和儿童心理学专家共同参与。",
    initiator: "编程小天才",
    budget: "35000",
    expectedOutput: "游戏设计文档",
    domainTags: ["教育培训"],
    customTags: ["儿童教育", "游戏化", "编程启蒙"],
    descriptionFiles: [],
    resourceFiles: [],
    endDate: "2026-06-01",
    contactEmail: "zhao@game.com",
    contactPhone: "134****2345",
    contactWeChat: "game_zhao",
    contactQQ: "654987321",
    createdAt: "2026-03-06",
    authorId: "user-005",
    authorName: "赵游戏",
    status: "共创中"
  },
  {
    id: "7",
    title: "医疗健康数据可视化平台",
    description: "开发一个面向医疗机构的健康数据可视化平台，需要数据分析师和医疗行业专家共同参与，探讨如何让复杂的医疗数据更易理解。",
    initiator: "健康数据科技",
    budget: "60000",
    expectedOutput: "可视化平台原型",
    domainTags: ["医疗健康", "生物医药"],
    customTags: ["数据可视化", "大数据"],
    descriptionFiles: [],
    resourceFiles: [],
    endDate: "2026-05-15",
    contactEmail: "sun@health.com",
    contactPhone: "133****6789",
    contactWeChat: "health_sun",
    contactQQ: "147258369",
    createdAt: "2026-03-08",
    authorId: "user-006",
    authorName: "孙医疗",
    status: "共创中"
  },
  {
    id: "8",
    title: "跨境电商物流追踪系统优化",
    description: "优化现有跨境电商的物流追踪系统，需要物流行业专家和后端开发者共同参与，提升用户对包裹状态的感知体验。",
    initiator: "全球购物流",
    budget: "40000",
    expectedOutput: "系统优化方案",
    domainTags: ["电子商务", "物流运输"],
    customTags: ["跨境电商", "系统优化"],
    descriptionFiles: [],
    resourceFiles: [],
    endDate: "2026-02-28",
    contactEmail: "qian@logistics.com",
    contactPhone: "132****4567",
    contactWeChat: "logistics_qian",
    contactQQ: "963852741",
    createdAt: "2026-01-10",
    authorId: "user-007",
    authorName: "钱物流",
    status: "已结束"
  },
  {
    id: "9",
    title: "虚拟现实旅游体验设计",
    description: "设计VR旅游体验产品，让用户足不出户也能感受世界各地的风景。需要VR开发者、旅游行业专家和3D建模师参与。",
    initiator: "VR旅行者",
    budget: "100000",
    expectedOutput: "VR体验Demo",
    domainTags: ["旅游酒店", "文化传媒"],
    customTags: ["VR", "沉浸式体验"],
    descriptionFiles: [],
    resourceFiles: [],
    endDate: "2026-05-30",
    contactEmail: "zhou@vr.com",
    contactPhone: "131****8901",
    contactWeChat: "vr_zhou",
    contactQQ: "852963741",
    createdAt: "2026-03-09",
    authorId: "user-008",
    authorName: "周虚拟",
    status: "共创中"
  },
  {
    id: "10",
    title: "老年人智能手机使用培训课程",
    description: "开发一套针对老年人的智能手机使用培训课程，需要老年教育专家、UI设计师和内容创作者共同参与。",
    initiator: "张设计工作室",
    budget: "20000",
    expectedOutput: "培训课程视频",
    domainTags: ["教育培训"],
    customTags: ["老年教育", "数字鸿沟", "培训课程"],
    descriptionFiles: [],
    resourceFiles: [],
    endDate: "2026-06-10",
    contactEmail: "wu@elder.com",
    contactPhone: "130****2345",
    contactWeChat: "elder_wu",
    contactQQ: "741852963",
    createdAt: "2026-03-10",
    authorId: "user-001",
    authorName: "张设计",
    status: "共创中"
  },
  {
    id: "11",
    title: "新能源汽车充电桩分布规划",
    description: "研究城市新能源汽车充电桩的合理分布规划，需要城市规划师、新能源行业专家和数据分析师参与。",
    initiator: "绿能出行",
    budget: "45000",
    expectedOutput: "规划报告",
    domainTags: ["新能源汽车", "智慧城市"],
    customTags: ["城市规划", "充电设施"],
    descriptionFiles: [],
    resourceFiles: [],
    endDate: "2026-04-25",
    contactEmail: "zheng@ev.com",
    contactPhone: "129****6789",
    contactWeChat: "ev_zheng",
    contactQQ: "369258147",
    createdAt: "2026-03-11",
    authorId: "user-009",
    authorName: "郑新能",
    status: "共创中"
  }
]
